/**
 * @file wifi_config.h
 * @brief Wi-Fi configuration for ESP-IDF
 */

#ifndef WIFI_CONFIG_H
#define WIFI_CONFIG_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>
#include "sdkconfig.h"
#include "esp_wifi.h"
#include "esp_err.h"
#include "esp_event.h"
#include "freertos/event_groups.h"

#define WIFI_MAXIMUM_RETRY 10
#define WIFI_CONNECT_TIMEOUT_MS 15000
#define WIFI_RECONNECT_DELAY_MS 5000
#define WIFI_MONITOR_PERIOD_MS 5000
#define WIFI_SCAN_PERIOD_MS 30000

#define WIFI_HOSTNAME "solar-inverter"

#ifndef CONFIG_INVERTER_WIFI_MODE_STA
#define CONFIG_INVERTER_WIFI_MODE_STA 0
#endif
#ifndef CONFIG_INVERTER_WIFI_MODE_AP
#define CONFIG_INVERTER_WIFI_MODE_AP 0
#endif
#ifndef CONFIG_INVERTER_WIFI_MODE_APSTA
#define CONFIG_INVERTER_WIFI_MODE_APSTA 1
#endif
#ifndef CONFIG_INVERTER_WIFI_AP_MAX_CONNECTION
#define CONFIG_INVERTER_WIFI_AP_MAX_CONNECTION 4
#endif
#ifndef CONFIG_INVERTER_WIFI_STA_SSID
#define CONFIG_INVERTER_WIFI_STA_SSID ""
#endif
#ifndef CONFIG_INVERTER_WIFI_STA_PASSWORD
#define CONFIG_INVERTER_WIFI_STA_PASSWORD ""
#endif
#ifndef CONFIG_INVERTER_WIFI_AP_SSID
#define CONFIG_INVERTER_WIFI_AP_SSID "Vonix-Inverter"
#endif
#ifndef CONFIG_INVERTER_WIFI_AP_PASSWORD
#define CONFIG_INVERTER_WIFI_AP_PASSWORD ""
#endif
#ifndef CONFIG_INVERTER_WIFI_AP_CHANNEL
#define CONFIG_INVERTER_WIFI_AP_CHANNEL 6
#endif
#ifndef CONFIG_INVERTER_WIFI_AUTH_MODE_WPA2_PSK
#define CONFIG_INVERTER_WIFI_AUTH_MODE_WPA2_PSK 0
#endif
#ifndef CONFIG_INVERTER_WIFI_AUTH_MODE_WPA3_PSK
#define CONFIG_INVERTER_WIFI_AUTH_MODE_WPA3_PSK 0
#endif
#ifndef CONFIG_INVERTER_WIFI_AUTH_MODE_WPA_WPA2_PSK
#define CONFIG_INVERTER_WIFI_AUTH_MODE_WPA_WPA2_PSK 0
#endif
#ifndef CONFIG_INVERTER_WIFI_RUNTIME_PROVISIONING
#define CONFIG_INVERTER_WIFI_RUNTIME_PROVISIONING 0
#endif

#define WIFI_COMPILED_STA_SSID CONFIG_INVERTER_WIFI_STA_SSID
#define WIFI_COMPILED_STA_PASSWORD CONFIG_INVERTER_WIFI_STA_PASSWORD
#define WIFI_COMPILED_AP_SSID CONFIG_INVERTER_WIFI_AP_SSID
#define WIFI_COMPILED_AP_PASSWORD CONFIG_INVERTER_WIFI_AP_PASSWORD
#define WIFI_COMPILED_AP_CHANNEL CONFIG_INVERTER_WIFI_AP_CHANNEL
#define WIFI_RUNTIME_PROVISIONING_ENABLED CONFIG_INVERTER_WIFI_RUNTIME_PROVISIONING
#define WIFI_AP_MAX_CONNECTION ((CONFIG_INVERTER_WIFI_AP_MAX_CONNECTION > 4) ? 4 : CONFIG_INVERTER_WIFI_AP_MAX_CONNECTION)
#define WIFI_AP_MAX_CLIENTS 4U

#if CONFIG_INVERTER_WIFI_MODE_STA
#define WIFI_COMPILED_OPERATION_MODE WIFI_MODE_STA
#define WIFI_COMPILED_OPERATION_MODE_NAME "STA"
#elif CONFIG_INVERTER_WIFI_MODE_AP
#define WIFI_COMPILED_OPERATION_MODE WIFI_MODE_AP
#define WIFI_COMPILED_OPERATION_MODE_NAME "AP"
#else
#define WIFI_COMPILED_OPERATION_MODE WIFI_MODE_APSTA
#define WIFI_COMPILED_OPERATION_MODE_NAME "APSTA"
#endif

#define WIFI_PROVISION_MAX_CONN WIFI_AP_MAX_CONNECTION

#if CONFIG_INVERTER_WIFI_AUTH_MODE_WPA3_PSK
#define INVERTER_WIFI_AUTH_MODE WIFI_AUTH_WPA3_PSK
#elif CONFIG_INVERTER_WIFI_AUTH_MODE_WPA2_PSK
#define INVERTER_WIFI_AUTH_MODE WIFI_AUTH_WPA2_PSK
#else
#define INVERTER_WIFI_AUTH_MODE WIFI_AUTH_WPA_WPA2_PSK
#endif

#define WIFI_USE_STATIC_IP false
#define WIFI_STATIC_IP "192.168.1.200"
#define WIFI_STATIC_GATEWAY "192.168.1.1"
#define WIFI_STATIC_NETMASK "255.255.255.0"
#define WIFI_STATIC_DNS "8.8.8.8"

#define WIFI_POWER_SAVE_MODE WIFI_PS_MIN_MODEM

#define WIFI_RSSI_EXCELLENT (-45)
#define WIFI_RSSI_GOOD (-60)
#define WIFI_RSSI_FAIR (-70)
#define WIFI_RSSI_WEAK (-80)

#define WIFI_NVS_NAMESPACE "wifi"

#if __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(WIFI_COMPILED_STA_SSID) <= 33U,
               "CONFIG_INVERTER_WIFI_STA_SSID exceeds the ESP32 SSID limit");
_Static_assert(sizeof(WIFI_COMPILED_STA_PASSWORD) <= 65U,
               "CONFIG_INVERTER_WIFI_STA_PASSWORD exceeds the WPA password limit");
_Static_assert(sizeof(WIFI_COMPILED_AP_SSID) <= 33U,
               "CONFIG_INVERTER_WIFI_AP_SSID exceeds the ESP32 SSID limit");
_Static_assert(sizeof(WIFI_COMPILED_AP_PASSWORD) <= 65U,
               "CONFIG_INVERTER_WIFI_AP_PASSWORD exceeds the WPA password limit");
_Static_assert(WIFI_COMPILED_AP_CHANNEL >= 1 && WIFI_COMPILED_AP_CHANNEL <= 13,
               "CONFIG_INVERTER_WIFI_AP_CHANNEL must be between 1 and 13");
_Static_assert((sizeof(WIFI_COMPILED_AP_PASSWORD) == 1U) ||
                   (sizeof(WIFI_COMPILED_AP_PASSWORD) >= 9U),
               "Access Point password must be empty or at least 8 characters");
#endif
#define WIFI_NVS_KEY_SSID "ssid"
#define WIFI_NVS_KEY_PASSWORD "password"
#define WIFI_NVS_KEY_STATIC_IP "static"
#define WIFI_NVS_KEY_DHCP "dhcp"

#define WIFI_HTTP_PORT 80
#define WIFI_HTTP_MAX_URI 8
#define WIFI_HTTP_STACK_SIZE 8192

#define WIFI_MONITOR_TASK_NAME "wifi_monitor"
#define WIFI_MONITOR_STACK_SIZE 6144
#define WIFI_MONITOR_PRIORITY 5

#define WIFI_MANAGER_TASK_NAME "wifi_manager"
#define WIFI_MANAGER_STACK_SIZE 6144
#define WIFI_MANAGER_PRIORITY 6

#define WIFI_MAX_SCAN_RESULTS 20
#define WIFI_SCAN_SHOW_HIDDEN true

#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT BIT1
#define WIFI_SCAN_DONE_BIT BIT2

    /* Defined in wifi_manager.c */
    extern EventGroupHandle_t wifi_event_group;

    typedef enum
    {
        WIFI_SIGNAL_NONE = 0,
        WIFI_SIGNAL_WEAK,
        WIFI_SIGNAL_FAIR,
        WIFI_SIGNAL_GOOD,
        WIFI_SIGNAL_EXCELLENT

    } wifi_signal_quality_t;

    typedef struct
    {
        char ssid[33];
        char password[64];

    } wifi_credentials_t;

#ifdef __cplusplus
}
#endif

#endif /* WIFI_CONFIG_H */