#ifndef INVERTER_ERRORS_H
#define INVERTER_ERRORS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    INVERTER_START_ERROR_NONE = 0x000,
    INVERTER_START_ERROR_POST = 0x101,
    INVERTER_START_ERROR_TELEMETRY = 0x102,
    INVERTER_START_ERROR_BATTERY_OVERVOLTAGE = 0x103,
    INVERTER_START_ERROR_BATTERY_UNDERVOLTAGE = 0x104,
    INVERTER_START_ERROR_GRID_VOLTAGE = 0x105,
    INVERTER_START_ERROR_GRID_FREQUENCY = 0x106,
    INVERTER_START_ERROR_DC_OVER_CURRENT = 0x107,
    INVERTER_START_ERROR_AC_OVER_CURRENT = 0x108,
    INVERTER_START_ERROR_OVERCURRENT = 0x109,
    INVERTER_START_ERROR_HEATSINK_TEMPERATURE = 0x10A,
    INVERTER_START_ERROR_TRANSFORMER_TEMPERATURE = 0x10B,
    INVERTER_START_ERROR_AMBIENT_TEMPERATURE = 0x10C,
    INVERTER_START_ERROR_SHORT_CIRCUIT = 0x10D,
    INVERTER_START_ERROR_GROUND_FAULT = 0x10E,
    INVERTER_START_ERROR_GATE_DRIVER = 0x10F,
    INVERTER_START_ERROR_DC_BUS_IMBALANCE = 0x110,
    INVERTER_START_ERROR_PRECHARGE = 0x111,
    INVERTER_START_ERROR_BATTERY_SOC = 0x112,
    INVERTER_START_ERROR_REVERSE_POLARITY = 0x113,
    INVERTER_START_ERROR_MINIMUM_OFF_TIME = 0x114,
    INVERTER_START_ERROR_EMERGENCY_STOP = 0x115,
    INVERTER_START_ERROR_ENCLOSURE = 0x116,
    INVERTER_START_ERROR_WATCHDOG = 0x117,
    INVERTER_START_ERROR_SAFETY = 0x1FF,
    INVERTER_START_ERROR_RELAY = 0x201,
} inverter_start_error_code_t;

void inverter_show_last_start_error(void);
inverter_start_error_code_t inverter_get_last_start_error_code(void);
const char *inverter_get_last_start_error_reason(void);

#ifdef __cplusplus
}
#endif

#endif
