#ifndef SYSTEM_ERROR_CODES_H
#define SYSTEM_ERROR_CODES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    SYSTEM_ERROR_NONE = 0x000,
    SYSTEM_ERROR_WIFI_INTERNET_UNAVAILABLE = 0x301,
    SYSTEM_ERROR_WIFI_NOT_CONNECTED = 0x302,
    SYSTEM_ERROR_WIFI_MODE_UNSUPPORTED = 0x303,
    SYSTEM_ERROR_WIFI_AP_CLIENT_LIMIT = 0x304,
    SYSTEM_ERROR_OTA_MANIFEST = 0x310,
    SYSTEM_ERROR_OTA_TRANSPORT = 0x311,
    SYSTEM_ERROR_PROTECTION_INVALID_TELEMETRY = 0x401,
    SYSTEM_ERROR_PROTECTION_INVALID_THRESHOLD = 0x402,
    SYSTEM_ERROR_PROTECTION_UNINITIALIZED = 0x403,
} system_error_code_t;

#ifdef __cplusplus
}
#endif

#endif /* SYSTEM_ERROR_CODES_H */
